# Generated by Django 3.1.7 on 2021-04-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonWeb', '0003_package_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='track_id',
        ),
    ]
