# Generated by Django 3.1.7 on 2021-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonWeb', '0006_remove_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='All', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
