# Generated by Django 3.1.7 on 2021-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonWeb', '0008_auto_20210417_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='track_num',
            field=models.IntegerField(default=-1),
        ),
    ]
