# Generated by Django 3.1.5 on 2021-04-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210423_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='initialized',
        ),
    ]
