# Generated by Django 3.1.6 on 2021-02-15 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20210215_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='passenger_num',
            new_name='passenger_number',
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
