# Generated by Django 3.1.7 on 2021-04-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('ups_account_name', models.CharField(blank=True, default='', max_length=50)),
                ('address_x', models.IntegerField(blank=True, default=-1)),
                ('address_y', models.IntegerField(blank=True, default=-1)),
            ],
        ),
    ]
