# Generated by Django 3.1.7 on 2021-04-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address_x',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='address_y',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressName', models.CharField(default='', max_length=200)),
                ('tag', models.CharField(blank=True, default='', max_length=30)),
                ('address_x', models.IntegerField(blank=True, default=-1)),
                ('address_y', models.IntegerField(blank=True, default=-1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.useraccount')),
            ],
        ),
    ]
