# Generated by Django 3.1.7 on 2021-04-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210422_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cardInfo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.useraccount'),
        ),
    ]
