# Generated by Django 3.1.5 on 2021-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_useraccount_initialized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='ups_account_name',
            new_name='ups_username',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ups_userid',
            field=models.IntegerField(default=-1),
        ),
    ]
