# Generated by Django 3.1.7 on 2021-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonWeb', '0004_remove_package_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
