# Generated by Django 3.1.7 on 2021-04-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonWeb', '0005_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
