# Generated by Django 3.1.5 on 2021-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonWeb', '0010_auto_20210419_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='ups_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
