# Generated by Django 3.1.6 on 2021-02-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210214_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
