version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=MATCH_ENGINE
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    

  server:
    user: root
    build: ./src
    command: bash -c "cd /temp && chmod o+x run.sh && ./run.sh"
    volumes:
      - ./src:/temp
    ports:
      - "12345:12345"
    depends_on:
      - db

      